"""Generate a pure-SQL seed file (``sql/04_seed.sql``) equivalent to
``scripts.seed``, for environments where running Python against the DB is
inconvenient (e.g. seeding Cloud SQL straight from TablePlus).

The only thing SQL cannot do is argon2 password hashing, so this script
pre-computes the hashes and embeds them as string literals. Everything else is
deterministic (uuid5) and idempotent (ON CONFLICT DO NOTHING).

    python -m scripts.gen_seed_sql        # writes sql/04_seed.sql

Re-run whenever the seed data or password scheme changes.
"""

from __future__ import annotations

import uuid
from pathlib import Path

from app.core.licensing.constants import CORE_MODULE_CODES, MODULE_CATALOG, ModuleCode
from app.core.security import hash_password
from app.modules.auth.permissions import RoleCode

# seed.py role matrix — keep in sync
from scripts.seed import ALL_CODES, ALL_PERMISSIONS, ROLE_MATRIX, ROLE_NAMES, TENANTS

NS = uuid.UUID("6ba7b810-9dad-11d1-80b4-00c04fd430c8")  # fixed → deterministic ids


def uid(*parts: str) -> str:
    return str(uuid.uuid5(NS, ":".join(parts)))


def q(val: str) -> str:
    """Single-quote + escape for SQL string literals."""
    return "'" + val.replace("'", "''") + "'"


# Users seeded per tenant: (local-part, full_name, RoleCode, password, is_superuser)
TENANT_USERS = [
    ("admin", "Tenant Admin", RoleCode.TENANT_ADMIN, "Admin123!", False),
    ("instructor", "Jane Instructor", RoleCode.INSTRUCTOR, "Teach123!", False),
    ("student", "Sam Student", RoleCode.STUDENT, "Learn123!", False),
]


def main() -> None:
    out: list[str] = []
    w = out.append

    w("-- GENERATED by scripts/gen_seed_sql.py — DO NOT hand-edit.")
    w("-- Pure-SQL equivalent of `python -m scripts.seed`.")
    w("-- Idempotent: safe to re-run. Run AFTER 01_schema.sql + 02_rls.sql.")
    w("-- Password hashes are argon2 (pwdlib) — precomputed at generation time.")
    w("")
    w("BEGIN;")
    w("-- platform-level seed: bypass row-level security for this transaction")
    w("SET LOCAL app.bypass_rls = 'on';")
    w("")

    # ── modules ────────────────────────────────────────────────────────────
    w("-- Module catalog (also covered by 03_seed_modules.sql; harmless repeat)")
    for code, desc in MODULE_CATALOG.items():
        is_core = "true" if code in CORE_MODULE_CODES else "false"
        w(
            "INSERT INTO modules (id, code, name, description, is_active, is_core) "
            f"VALUES (gen_random_uuid(), {q(code.value)}, {q(desc)}, {q(desc)}, true, {is_core}) "
            "ON CONFLICT (code) DO NOTHING;"
        )
    w("")

    # ── permissions ──────────────────────────────────────────────────────────
    w("-- Global permission catalog")
    for code, desc in ALL_PERMISSIONS:
        w(
            "INSERT INTO permissions (id, code, description) "
            f"VALUES (gen_random_uuid(), {q(code)}, {q(desc)}) "
            "ON CONFLICT (code) DO NOTHING;"
        )
    w("")

    # ── per-tenant ───────────────────────────────────────────────────────────
    for slug, (name, modules) in TENANTS.items():
        tenant_id = uid("tenant", slug)
        w(f"-- ===== tenant: {slug} ({name}) =====")
        w(
            "INSERT INTO tenants (id, name, slug, is_active, isolation_mode, settings) "
            f"VALUES ({q(tenant_id)}, {q(name)}, {q(slug)}, true, 'shared', '{{}}'::jsonb) "
            "ON CONFLICT (slug) DO NOTHING;"
        )

        # licensing (reference module by code so it works even if ids differ)
        w("-- licensed modules")
        for code in modules:
            tm_id = uid("tenant_module", slug, code.value)
            w(
                "INSERT INTO tenant_modules (id, tenant_id, module_id, enabled, enabled_at) "
                f"SELECT {q(tm_id)}, {q(tenant_id)}, m.id, true, now() "
                f"FROM modules m WHERE m.code = {q(code.value)} "
                "ON CONFLICT (tenant_id, module_id) DO NOTHING;"
            )

        # roles + role_permissions
        w("-- roles")
        for rc in RoleCode:
            role_id = uid("role", slug, rc.value)
            w(
                "INSERT INTO roles (id, tenant_id, code, name, is_system) "
                f"VALUES ({q(role_id)}, {q(tenant_id)}, {q(rc.value)}, {q(ROLE_NAMES[rc])}, true) "
                "ON CONFLICT (tenant_id, code) DO NOTHING;"
            )
            codes = sorted(ROLE_MATRIX[rc] & ALL_CODES)
            if codes:
                in_list = ", ".join(q(c) for c in codes)
                w(
                    "INSERT INTO role_permissions (role_id, permission_id) "
                    f"SELECT {q(role_id)}, p.id FROM permissions p WHERE p.code IN ({in_list}) "
                    "ON CONFLICT DO NOTHING;"
                )

        # users + user_roles
        w("-- users (login via header  X-Tenant-ID: " + slug + ")")
        domain = f"{slug}.com"
        users = list(TENANT_USERS)
        if slug == "full-lms":
            users = users + [
                ("root@platform.com", "Platform Root", RoleCode.SUPER_ADMIN, "Root123!", True)
            ]
        for local, full_name, rc, password, is_super in users:
            email = local if "@" in local else f"{local}@{domain}"
            user_id = uid("user", slug, email)
            role_id = uid("role", slug, rc.value)
            w(
                "INSERT INTO users "
                "(id, tenant_id, email, hashed_password, full_name, is_active, is_verified, is_superuser) "
                f"VALUES ({q(user_id)}, {q(tenant_id)}, {q(email)}, {q(hash_password(password))}, "
                f"{q(full_name)}, true, true, {'true' if is_super else 'false'}) "
                "ON CONFLICT (tenant_id, email) DO NOTHING;"
            )
            w(
                "INSERT INTO user_roles (user_id, role_id) "
                f"VALUES ({q(user_id)}, {q(role_id)}) ON CONFLICT DO NOTHING;"
            )

        # content: category + published course + module + 2 lessons
        w("-- sample content")
        cat_id = uid("category", slug, "programming")
        course_id = uid("course", slug, "python-for-beginners")
        cmod_id = uid("course_module", slug, "getting-started")
        l1_id = uid("lesson", slug, "welcome")
        l2_id = uid("lesson", slug, "installing-python")
        w(
            "INSERT INTO categories (id, tenant_id, name, slug) "
            f"VALUES ({q(cat_id)}, {q(tenant_id)}, 'Programming', 'programming') "
            "ON CONFLICT (tenant_id, slug) DO NOTHING;"
        )
        w(
            "INSERT INTO courses (id, tenant_id, title, slug, summary, description, category_id, "
            "status, level, is_free, price, enrollment_count, published_at) "
            f"VALUES ({q(course_id)}, {q(tenant_id)}, 'Python for Beginners', "
            "'python-for-beginners', 'Learn Python from scratch.', "
            f"'A complete introduction to Python programming.', {q(cat_id)}, "
            "'published', 'beginner', true, 0, 0, now()) "
            "ON CONFLICT (tenant_id, slug) DO NOTHING;"
        )
        w(
            "INSERT INTO course_modules (id, tenant_id, course_id, title, order_index) "
            f"VALUES ({q(cmod_id)}, {q(tenant_id)}, {q(course_id)}, 'Getting Started', 0) "
            "ON CONFLICT (id) DO NOTHING;"
        )
        w(
            "INSERT INTO lessons (id, tenant_id, course_id, module_id, title, content_type, "
            "content, order_index, duration_seconds, is_preview) "
            f"VALUES ({q(l1_id)}, {q(tenant_id)}, {q(course_id)}, {q(cmod_id)}, 'Welcome', "
            "'text', 'Welcome to the course!', 0, 0, true) ON CONFLICT (id) DO NOTHING;"
        )
        w(
            "INSERT INTO lessons (id, tenant_id, course_id, module_id, title, content_type, "
            "content, order_index, duration_seconds, is_preview) "
            f"VALUES ({q(l2_id)}, {q(tenant_id)}, {q(course_id)}, {q(cmod_id)}, "
            "'Installing Python', 'video', NULL, 1, 600, false) ON CONFLICT (id) DO NOTHING;"
        )

        # quiz only for full-lms (ASSIGNMENTS licensed)
        if slug == "full-lms":
            a_id = uid("assignment", slug, "python-basics-quiz")
            quiz_id = uid("quiz", slug, "python-basics-quiz")
            qq_id = uid("question", slug, "def-keyword")
            w("-- quiz (full-lms has the ASSIGNMENTS module)")
            w(
                "INSERT INTO assignments (id, tenant_id, course_id, title, description, type, "
                "max_points, pass_points, is_published) "
                f"VALUES ({q(a_id)}, {q(tenant_id)}, {q(course_id)}, 'Python Basics Quiz', "
                "'Check your understanding.', 'quiz', 10, 6, true) ON CONFLICT (id) DO NOTHING;"
            )
            w(
                "INSERT INTO quizzes (id, tenant_id, assignment_id, time_limit_seconds, shuffle_questions) "
                f"VALUES ({q(quiz_id)}, {q(tenant_id)}, {q(a_id)}, 0, false) "
                "ON CONFLICT (assignment_id) DO NOTHING;"
            )
            w(
                "INSERT INTO quiz_questions (id, tenant_id, quiz_id, text, type, points, order_index) "
                f"VALUES ({q(qq_id)}, {q(tenant_id)}, {q(quiz_id)}, "
                "'What keyword defines a function in Python?', 'single', 10, 0) "
                "ON CONFLICT (id) DO NOTHING;"
            )
            for ans, correct in [("def", True), ("func", False), ("lambda", False)]:
                ans_id = uid("answer", slug, "def-keyword", ans)
                w(
                    "INSERT INTO quiz_answers (id, tenant_id, question_id, text, is_correct) "
                    f"VALUES ({q(ans_id)}, {q(tenant_id)}, {q(qq_id)}, {q(ans)}, "
                    f"{'true' if correct else 'false'}) ON CONFLICT (id) DO NOTHING;"
                )
        w("")

    w("COMMIT;")
    w("")
    w("-- Login (send header  X-Tenant-ID: <slug>):")
    w("--   admin@abc-academy.com / Admin123!")
    w("--   student@full-lms.com  / Learn123!")
    w("--   root@platform.com     / Root123!   (super admin)")
    w("")

    target = Path(__file__).resolve().parent.parent / "sql" / "04_seed.sql"
    target.write_text("\n".join(out))
    print(f"Wrote {target} ({len(out)} lines)")


if __name__ == "__main__":
    main()
