-- GENERATED by scripts/gen_seed_sql.py — DO NOT hand-edit.
-- Pure-SQL equivalent of `python -m scripts.seed`.
-- Idempotent: safe to re-run. Run AFTER 01_schema.sql + 02_rls.sql.
-- Password hashes are argon2 (pwdlib) — precomputed at generation time.

BEGIN;
-- platform-level seed: bypass row-level security for this transaction
SET LOCAL app.bypass_rls = 'on';

-- Module catalog (also covered by 03_seed_modules.sql; harmless repeat)
INSERT INTO modules (id, code, name, description, is_active, is_core) VALUES (gen_random_uuid(), 'AUTH', 'Authentication & identity', 'Authentication & identity', true, true) ON CONFLICT (code) DO NOTHING;
INSERT INTO modules (id, code, name, description, is_active, is_core) VALUES (gen_random_uuid(), 'COURSES', 'Course catalog & enrollment', 'Course catalog & enrollment', true, false) ON CONFLICT (code) DO NOTHING;
INSERT INTO modules (id, code, name, description, is_active, is_core) VALUES (gen_random_uuid(), 'LEARNING', 'Lessons, content & progress', 'Lessons, content & progress', true, false) ON CONFLICT (code) DO NOTHING;
INSERT INTO modules (id, code, name, description, is_active, is_core) VALUES (gen_random_uuid(), 'ASSIGNMENTS', 'Assignments, quizzes & grading', 'Assignments, quizzes & grading', true, false) ON CONFLICT (code) DO NOTHING;
INSERT INTO modules (id, code, name, description, is_active, is_core) VALUES (gen_random_uuid(), 'DASHBOARD', 'Learner & instructor dashboards', 'Learner & instructor dashboards', true, false) ON CONFLICT (code) DO NOTHING;
INSERT INTO modules (id, code, name, description, is_active, is_core) VALUES (gen_random_uuid(), 'ADMIN', 'Administration, reports & analytics', 'Administration, reports & analytics', true, false) ON CONFLICT (code) DO NOTHING;

-- Global permission catalog
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'user:read', 'View users') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'user:create', 'Create users') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'user:update', 'Update users') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'user:delete', 'Delete users') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'role:read', 'View roles') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'role:assign', 'Assign roles to users') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'tenant:read', 'View tenant settings') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'tenant:manage', 'Manage tenants & module licensing') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'course:read', 'View courses') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'course:create', 'Create courses') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'course:update', 'Update courses') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'course:delete', 'Delete courses') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'course:enroll', 'Enroll in courses') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'category:manage', 'Manage categories') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'lesson:read', 'View lessons') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'lesson:create', 'Create lessons') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'lesson:update', 'Update lessons') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'lesson:delete', 'Delete lessons') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'progress:read', 'View own progress') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'assignment:read', 'View assignments') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'assignment:create', 'Create assignments') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'assignment:update', 'Update assignments') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'assignment:delete', 'Delete assignments') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'assignment:submit', 'Submit assignments') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'grade:read', 'View grades') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'grade:write', 'Grade submissions') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'report:read', 'View reports & analytics') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (id, code, description) VALUES (gen_random_uuid(), 'admin:access', 'Access the admin module') ON CONFLICT (code) DO NOTHING;

-- ===== tenant: abc-academy (ABC Academy) =====
INSERT INTO tenants (id, name, slug, is_active, isolation_mode, settings) VALUES ('9efe352d-9b8a-5511-b1d2-e392b13ca274', 'ABC Academy', 'abc-academy', true, 'shared', '{}'::jsonb) ON CONFLICT (slug) DO NOTHING;
-- licensed modules
INSERT INTO tenant_modules (id, tenant_id, module_id, enabled, enabled_at) SELECT '625fb148-5c45-514e-a925-3ab6834953c8', '9efe352d-9b8a-5511-b1d2-e392b13ca274', m.id, true, now() FROM modules m WHERE m.code = 'AUTH' ON CONFLICT (tenant_id, module_id) DO NOTHING;
INSERT INTO tenant_modules (id, tenant_id, module_id, enabled, enabled_at) SELECT '4a17d505-8b12-5a25-80c4-376ba45fac28', '9efe352d-9b8a-5511-b1d2-e392b13ca274', m.id, true, now() FROM modules m WHERE m.code = 'COURSES' ON CONFLICT (tenant_id, module_id) DO NOTHING;
INSERT INTO tenant_modules (id, tenant_id, module_id, enabled, enabled_at) SELECT '02b74aa8-3f4c-5999-9ef2-da41c6ae560e', '9efe352d-9b8a-5511-b1d2-e392b13ca274', m.id, true, now() FROM modules m WHERE m.code = 'LEARNING' ON CONFLICT (tenant_id, module_id) DO NOTHING;
-- roles
INSERT INTO roles (id, tenant_id, code, name, is_system) VALUES ('5e7e940c-aca8-58e8-b107-4cd526d3fb9d', '9efe352d-9b8a-5511-b1d2-e392b13ca274', 'super_admin', 'Super Admin', true) ON CONFLICT (tenant_id, code) DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT '5e7e940c-aca8-58e8-b107-4cd526d3fb9d', p.id FROM permissions p WHERE p.code IN ('admin:access', 'assignment:create', 'assignment:delete', 'assignment:read', 'assignment:submit', 'assignment:update', 'category:manage', 'course:create', 'course:delete', 'course:enroll', 'course:read', 'course:update', 'grade:read', 'grade:write', 'lesson:create', 'lesson:delete', 'lesson:read', 'lesson:update', 'progress:read', 'report:read', 'role:assign', 'role:read', 'tenant:manage', 'tenant:read', 'user:create', 'user:delete', 'user:read', 'user:update') ON CONFLICT DO NOTHING;
INSERT INTO roles (id, tenant_id, code, name, is_system) VALUES ('ec2f3762-ba58-5828-9dd7-9405dee59a41', '9efe352d-9b8a-5511-b1d2-e392b13ca274', 'tenant_admin', 'Tenant Admin', true) ON CONFLICT (tenant_id, code) DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT 'ec2f3762-ba58-5828-9dd7-9405dee59a41', p.id FROM permissions p WHERE p.code IN ('admin:access', 'assignment:create', 'assignment:delete', 'assignment:read', 'assignment:submit', 'assignment:update', 'category:manage', 'course:create', 'course:delete', 'course:enroll', 'course:read', 'course:update', 'grade:read', 'grade:write', 'lesson:create', 'lesson:delete', 'lesson:read', 'lesson:update', 'progress:read', 'report:read', 'role:assign', 'role:read', 'tenant:read', 'user:create', 'user:delete', 'user:read', 'user:update') ON CONFLICT DO NOTHING;
INSERT INTO roles (id, tenant_id, code, name, is_system) VALUES ('7e6fe1aa-fa0b-5897-a088-e0c22856645e', '9efe352d-9b8a-5511-b1d2-e392b13ca274', 'instructor', 'Instructor', true) ON CONFLICT (tenant_id, code) DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT '7e6fe1aa-fa0b-5897-a088-e0c22856645e', p.id FROM permissions p WHERE p.code IN ('admin:access', 'assignment:create', 'assignment:read', 'assignment:update', 'category:manage', 'course:create', 'course:read', 'course:update', 'grade:read', 'grade:write', 'lesson:create', 'lesson:delete', 'lesson:read', 'lesson:update', 'progress:read', 'report:read', 'user:read') ON CONFLICT DO NOTHING;
INSERT INTO roles (id, tenant_id, code, name, is_system) VALUES ('841eaf4a-b1db-5fcd-81a3-6ff5244d3be1', '9efe352d-9b8a-5511-b1d2-e392b13ca274', 'student', 'Student', true) ON CONFLICT (tenant_id, code) DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT '841eaf4a-b1db-5fcd-81a3-6ff5244d3be1', p.id FROM permissions p WHERE p.code IN ('assignment:read', 'assignment:submit', 'course:enroll', 'course:read', 'grade:read', 'lesson:read', 'progress:read') ON CONFLICT DO NOTHING;
-- users (login via header  X-Tenant-ID: abc-academy)
INSERT INTO users (id, tenant_id, email, hashed_password, full_name, is_active, is_verified, is_superuser) VALUES ('69f3c941-2412-50f4-a042-48d23f8fa980', '9efe352d-9b8a-5511-b1d2-e392b13ca274', 'admin@abc-academy.com', '$argon2id$v=19$m=65536,t=3,p=4$hiCRmLMSmOhOfaF2Lfug4A$t6mkrNRgxsBedsGHZUHKbzSn2uxtijKUjE7GhzWb1sU', 'Tenant Admin', true, true, false) ON CONFLICT (tenant_id, email) DO NOTHING;
INSERT INTO user_roles (user_id, role_id) VALUES ('69f3c941-2412-50f4-a042-48d23f8fa980', 'ec2f3762-ba58-5828-9dd7-9405dee59a41') ON CONFLICT DO NOTHING;
INSERT INTO users (id, tenant_id, email, hashed_password, full_name, is_active, is_verified, is_superuser) VALUES ('8c91f5f0-5ddb-5484-8b56-b440cee0736e', '9efe352d-9b8a-5511-b1d2-e392b13ca274', 'instructor@abc-academy.com', '$argon2id$v=19$m=65536,t=3,p=4$lwqbKVf8LRQIjD9BlWY9FA$oz8wdHywLjvh54lg1rz3URbdj1ryo0KsM4GZTdpXO+o', 'Jane Instructor', true, true, false) ON CONFLICT (tenant_id, email) DO NOTHING;
INSERT INTO user_roles (user_id, role_id) VALUES ('8c91f5f0-5ddb-5484-8b56-b440cee0736e', '7e6fe1aa-fa0b-5897-a088-e0c22856645e') ON CONFLICT DO NOTHING;
INSERT INTO users (id, tenant_id, email, hashed_password, full_name, is_active, is_verified, is_superuser) VALUES ('bbe454eb-8f91-5648-8fea-805c65455d07', '9efe352d-9b8a-5511-b1d2-e392b13ca274', 'student@abc-academy.com', '$argon2id$v=19$m=65536,t=3,p=4$Q9zkFdZNkWapmzrrlHPTeQ$SN81u+NAYJsPYUpg0Z4aaPQ8RVB5glBX9+UZ1eGqVHc', 'Sam Student', true, true, false) ON CONFLICT (tenant_id, email) DO NOTHING;
INSERT INTO user_roles (user_id, role_id) VALUES ('bbe454eb-8f91-5648-8fea-805c65455d07', '841eaf4a-b1db-5fcd-81a3-6ff5244d3be1') ON CONFLICT DO NOTHING;
-- sample content
INSERT INTO categories (id, tenant_id, name, slug) VALUES ('093ceb29-3c73-5f38-8290-95d81f995c40', '9efe352d-9b8a-5511-b1d2-e392b13ca274', 'Programming', 'programming') ON CONFLICT (tenant_id, slug) DO NOTHING;
INSERT INTO courses (id, tenant_id, title, slug, summary, description, category_id, status, level, is_free, price, enrollment_count, published_at) VALUES ('a183f69f-1935-524a-8ca1-9a16c92e7435', '9efe352d-9b8a-5511-b1d2-e392b13ca274', 'Python for Beginners', 'python-for-beginners', 'Learn Python from scratch.', 'A complete introduction to Python programming.', '093ceb29-3c73-5f38-8290-95d81f995c40', 'published', 'beginner', true, 0, 0, now()) ON CONFLICT (tenant_id, slug) DO NOTHING;
INSERT INTO course_modules (id, tenant_id, course_id, title, order_index) VALUES ('ee0f74f7-df7d-58d3-bd0f-d0f7cff5c7ba', '9efe352d-9b8a-5511-b1d2-e392b13ca274', 'a183f69f-1935-524a-8ca1-9a16c92e7435', 'Getting Started', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, tenant_id, course_id, module_id, title, content_type, content, order_index, duration_seconds, is_preview) VALUES ('aa901e8e-2188-5067-bb76-26bf0e806405', '9efe352d-9b8a-5511-b1d2-e392b13ca274', 'a183f69f-1935-524a-8ca1-9a16c92e7435', 'ee0f74f7-df7d-58d3-bd0f-d0f7cff5c7ba', 'Welcome', 'text', 'Welcome to the course!', 0, 0, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, tenant_id, course_id, module_id, title, content_type, content, order_index, duration_seconds, is_preview) VALUES ('98eab508-3520-50b2-a592-7fdb4b9f946b', '9efe352d-9b8a-5511-b1d2-e392b13ca274', 'a183f69f-1935-524a-8ca1-9a16c92e7435', 'ee0f74f7-df7d-58d3-bd0f-d0f7cff5c7ba', 'Installing Python', 'video', NULL, 1, 600, false) ON CONFLICT (id) DO NOTHING;

-- ===== tenant: full-lms (Full LMS Inc) =====
INSERT INTO tenants (id, name, slug, is_active, isolation_mode, settings) VALUES ('db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'Full LMS Inc', 'full-lms', true, 'shared', '{}'::jsonb) ON CONFLICT (slug) DO NOTHING;
-- licensed modules
INSERT INTO tenant_modules (id, tenant_id, module_id, enabled, enabled_at) SELECT 'f3ceffb1-65ce-5fd9-bbdd-d638ebde0135', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', m.id, true, now() FROM modules m WHERE m.code = 'AUTH' ON CONFLICT (tenant_id, module_id) DO NOTHING;
INSERT INTO tenant_modules (id, tenant_id, module_id, enabled, enabled_at) SELECT '197eda87-8cc8-5419-bfc8-5a1a9d74b328', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', m.id, true, now() FROM modules m WHERE m.code = 'COURSES' ON CONFLICT (tenant_id, module_id) DO NOTHING;
INSERT INTO tenant_modules (id, tenant_id, module_id, enabled, enabled_at) SELECT '4ac859aa-88dd-508e-94b9-90aeba13a345', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', m.id, true, now() FROM modules m WHERE m.code = 'LEARNING' ON CONFLICT (tenant_id, module_id) DO NOTHING;
INSERT INTO tenant_modules (id, tenant_id, module_id, enabled, enabled_at) SELECT '086fb4f0-69e8-523b-b4e3-d9f0555b7bd9', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', m.id, true, now() FROM modules m WHERE m.code = 'ASSIGNMENTS' ON CONFLICT (tenant_id, module_id) DO NOTHING;
INSERT INTO tenant_modules (id, tenant_id, module_id, enabled, enabled_at) SELECT '4fffe2c4-adb4-52aa-a1a0-1e293ba68535', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', m.id, true, now() FROM modules m WHERE m.code = 'DASHBOARD' ON CONFLICT (tenant_id, module_id) DO NOTHING;
INSERT INTO tenant_modules (id, tenant_id, module_id, enabled, enabled_at) SELECT '0d57df99-223f-52f2-93ed-95b8f34714a6', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', m.id, true, now() FROM modules m WHERE m.code = 'ADMIN' ON CONFLICT (tenant_id, module_id) DO NOTHING;
-- roles
INSERT INTO roles (id, tenant_id, code, name, is_system) VALUES ('af754129-e4f6-5c0b-b496-b49b961bda8f', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'super_admin', 'Super Admin', true) ON CONFLICT (tenant_id, code) DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT 'af754129-e4f6-5c0b-b496-b49b961bda8f', p.id FROM permissions p WHERE p.code IN ('admin:access', 'assignment:create', 'assignment:delete', 'assignment:read', 'assignment:submit', 'assignment:update', 'category:manage', 'course:create', 'course:delete', 'course:enroll', 'course:read', 'course:update', 'grade:read', 'grade:write', 'lesson:create', 'lesson:delete', 'lesson:read', 'lesson:update', 'progress:read', 'report:read', 'role:assign', 'role:read', 'tenant:manage', 'tenant:read', 'user:create', 'user:delete', 'user:read', 'user:update') ON CONFLICT DO NOTHING;
INSERT INTO roles (id, tenant_id, code, name, is_system) VALUES ('1ce04fd0-55de-59f8-b396-e65b536a0ef8', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'tenant_admin', 'Tenant Admin', true) ON CONFLICT (tenant_id, code) DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT '1ce04fd0-55de-59f8-b396-e65b536a0ef8', p.id FROM permissions p WHERE p.code IN ('admin:access', 'assignment:create', 'assignment:delete', 'assignment:read', 'assignment:submit', 'assignment:update', 'category:manage', 'course:create', 'course:delete', 'course:enroll', 'course:read', 'course:update', 'grade:read', 'grade:write', 'lesson:create', 'lesson:delete', 'lesson:read', 'lesson:update', 'progress:read', 'report:read', 'role:assign', 'role:read', 'tenant:read', 'user:create', 'user:delete', 'user:read', 'user:update') ON CONFLICT DO NOTHING;
INSERT INTO roles (id, tenant_id, code, name, is_system) VALUES ('14242dea-c3c2-5ac8-a1a9-72b545f6c341', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'instructor', 'Instructor', true) ON CONFLICT (tenant_id, code) DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT '14242dea-c3c2-5ac8-a1a9-72b545f6c341', p.id FROM permissions p WHERE p.code IN ('admin:access', 'assignment:create', 'assignment:read', 'assignment:update', 'category:manage', 'course:create', 'course:read', 'course:update', 'grade:read', 'grade:write', 'lesson:create', 'lesson:delete', 'lesson:read', 'lesson:update', 'progress:read', 'report:read', 'user:read') ON CONFLICT DO NOTHING;
INSERT INTO roles (id, tenant_id, code, name, is_system) VALUES ('43e2835f-12fa-5ca5-a564-920ab0daf2f5', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'student', 'Student', true) ON CONFLICT (tenant_id, code) DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT '43e2835f-12fa-5ca5-a564-920ab0daf2f5', p.id FROM permissions p WHERE p.code IN ('assignment:read', 'assignment:submit', 'course:enroll', 'course:read', 'grade:read', 'lesson:read', 'progress:read') ON CONFLICT DO NOTHING;
-- users (login via header  X-Tenant-ID: full-lms)
INSERT INTO users (id, tenant_id, email, hashed_password, full_name, is_active, is_verified, is_superuser) VALUES ('699efcad-fc50-5ceb-bb46-9b48d163db72', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'admin@full-lms.com', '$argon2id$v=19$m=65536,t=3,p=4$bTC6iB4VEXrI8mx6zH9yNw$mNTWxVFsOA8heNy7iQS2IrlDzvlVS5PBzHgvsNn3LLY', 'Tenant Admin', true, true, false) ON CONFLICT (tenant_id, email) DO NOTHING;
INSERT INTO user_roles (user_id, role_id) VALUES ('699efcad-fc50-5ceb-bb46-9b48d163db72', '1ce04fd0-55de-59f8-b396-e65b536a0ef8') ON CONFLICT DO NOTHING;
INSERT INTO users (id, tenant_id, email, hashed_password, full_name, is_active, is_verified, is_superuser) VALUES ('bdfb51b7-8b38-5bea-8fc0-b33a25b94c97', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'instructor@full-lms.com', '$argon2id$v=19$m=65536,t=3,p=4$bUPr+27ofFzdmwL6GPpnzw$FFFYHD8R8xDoEgVF+67MlQrIy/lPbrGVLFYU1tdFcD8', 'Jane Instructor', true, true, false) ON CONFLICT (tenant_id, email) DO NOTHING;
INSERT INTO user_roles (user_id, role_id) VALUES ('bdfb51b7-8b38-5bea-8fc0-b33a25b94c97', '14242dea-c3c2-5ac8-a1a9-72b545f6c341') ON CONFLICT DO NOTHING;
INSERT INTO users (id, tenant_id, email, hashed_password, full_name, is_active, is_verified, is_superuser) VALUES ('fed74fbb-3875-5c54-b8af-c42fc9d9b5a3', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'student@full-lms.com', '$argon2id$v=19$m=65536,t=3,p=4$lHK/ZyPY/SpPx4pyZhUZzA$IjuYA4Elo3rYtg/Esm4hRPxdOu3fon9t9rvG4rH35Dk', 'Sam Student', true, true, false) ON CONFLICT (tenant_id, email) DO NOTHING;
INSERT INTO user_roles (user_id, role_id) VALUES ('fed74fbb-3875-5c54-b8af-c42fc9d9b5a3', '43e2835f-12fa-5ca5-a564-920ab0daf2f5') ON CONFLICT DO NOTHING;
INSERT INTO users (id, tenant_id, email, hashed_password, full_name, is_active, is_verified, is_superuser) VALUES ('961a6869-1e24-5aac-8732-dd29b118cfb6', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'root@platform.com', '$argon2id$v=19$m=65536,t=3,p=4$vtJnvss48PKXlh9y64ebHw$Ylsm0u8vA8KPeE0Wngouo9DUypfV0HgSfybwxUoOcGg', 'Platform Root', true, true, true) ON CONFLICT (tenant_id, email) DO NOTHING;
INSERT INTO user_roles (user_id, role_id) VALUES ('961a6869-1e24-5aac-8732-dd29b118cfb6', 'af754129-e4f6-5c0b-b496-b49b961bda8f') ON CONFLICT DO NOTHING;
-- sample content
INSERT INTO categories (id, tenant_id, name, slug) VALUES ('f388b8b8-dc88-5dac-b436-edf41eeb12b1', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'Programming', 'programming') ON CONFLICT (tenant_id, slug) DO NOTHING;
INSERT INTO courses (id, tenant_id, title, slug, summary, description, category_id, status, level, is_free, price, enrollment_count, published_at) VALUES ('fa5bd3e3-388b-572a-a781-12fb8c759213', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'Python for Beginners', 'python-for-beginners', 'Learn Python from scratch.', 'A complete introduction to Python programming.', 'f388b8b8-dc88-5dac-b436-edf41eeb12b1', 'published', 'beginner', true, 0, 0, now()) ON CONFLICT (tenant_id, slug) DO NOTHING;
INSERT INTO course_modules (id, tenant_id, course_id, title, order_index) VALUES ('1bef28f8-e815-59bb-a8c2-86504be3322d', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'fa5bd3e3-388b-572a-a781-12fb8c759213', 'Getting Started', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, tenant_id, course_id, module_id, title, content_type, content, order_index, duration_seconds, is_preview) VALUES ('962bd6d2-9343-5187-ad26-1f4102a9b215', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'fa5bd3e3-388b-572a-a781-12fb8c759213', '1bef28f8-e815-59bb-a8c2-86504be3322d', 'Welcome', 'text', 'Welcome to the course!', 0, 0, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, tenant_id, course_id, module_id, title, content_type, content, order_index, duration_seconds, is_preview) VALUES ('191d5697-cac4-5c75-906c-99d3261daf30', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'fa5bd3e3-388b-572a-a781-12fb8c759213', '1bef28f8-e815-59bb-a8c2-86504be3322d', 'Installing Python', 'video', NULL, 1, 600, false) ON CONFLICT (id) DO NOTHING;
-- quiz (full-lms has the ASSIGNMENTS module)
INSERT INTO assignments (id, tenant_id, course_id, title, description, type, max_points, pass_points, is_published) VALUES ('e9b9c859-2bd7-5a68-b60b-74685b649290', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'fa5bd3e3-388b-572a-a781-12fb8c759213', 'Python Basics Quiz', 'Check your understanding.', 'quiz', 10, 6, true) ON CONFLICT (id) DO NOTHING;
INSERT INTO quizzes (id, tenant_id, assignment_id, time_limit_seconds, shuffle_questions) VALUES ('08cdc89f-0f96-5132-b67e-458ead8f46c6', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'e9b9c859-2bd7-5a68-b60b-74685b649290', 0, false) ON CONFLICT (assignment_id) DO NOTHING;
INSERT INTO quiz_questions (id, tenant_id, quiz_id, text, type, points, order_index) VALUES ('cb08f272-1a88-594b-b92b-9f3adcdf24c6', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', '08cdc89f-0f96-5132-b67e-458ead8f46c6', 'What keyword defines a function in Python?', 'single', 10, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO quiz_answers (id, tenant_id, question_id, text, is_correct) VALUES ('c6666692-9a32-507b-8c20-a6a5188cf29c', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'cb08f272-1a88-594b-b92b-9f3adcdf24c6', 'def', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO quiz_answers (id, tenant_id, question_id, text, is_correct) VALUES ('4c74784d-e6ad-5e15-af32-b95df0087843', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'cb08f272-1a88-594b-b92b-9f3adcdf24c6', 'func', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO quiz_answers (id, tenant_id, question_id, text, is_correct) VALUES ('768d2288-8d30-5a9e-99e5-c5266d420315', 'db98c48b-9ea9-5ee5-8dbd-1b1e5c375d79', 'cb08f272-1a88-594b-b92b-9f3adcdf24c6', 'lambda', false) ON CONFLICT (id) DO NOTHING;

COMMIT;

-- Login (send header  X-Tenant-ID: <slug>):
--   admin@abc-academy.com / Admin123!
--   student@full-lms.com  / Learn123!
--   root@platform.com     / Root123!   (super admin)
